# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Automation of tests app"
  lane :tests do
    # run_tests(scheme: "MyAppTests")
    discord_notifier(
    webhook_url:"https://discord.com/api/webhooks/1246649780340391966/G-3F9LvurenNIBqYoaz_Fn-6SFEyCLpAXppsgQ3niw8-vlSY2rOQYyNF8lu6NmYZdqc1",
    title: "App testing",
    description: "Fastlane is testing your app",
  )
  end


  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
