# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Release to Firebase Distribution"
  lane :release_to_firebase_distribution do
    firebase_app_distribution(
      app: "1:474571213215:android:b095729cceb0c1261115aa",
      groups: "test_1",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      release_notes: "Test releases",
      apk_path: "../build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      debug: true
    )
    send_discord(environment: "firebase", flavor: "dev")
  end

  desc "Notification discord for distribute app"
  lane :send_discord do |options|
    destination=options[:environment]=="appstore" ? "Google Play" : "Firebase Distribution"
    env = options[:environment]
    flavor = options[:flavor]

    discord_notifier(
      webhook_url:"https://discord.com/api/webhooks/1246649780340391966/G-3F9LvurenNIBqYoaz_Fn-6SFEyCLpAXppsgQ3niw8-vlSY2rOQYyNF8lu6NmYZdqc1",
      title: "App's distributing to `#{destination}`",
      description: "Release app Android done via `#{destination}`! \nFlavor: `#{flavor}`\nEnvironment: `#{env}`\nRelease note: Testing",
    )
  end
end
